name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-xdist mypy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pytest with XML report
        run: pytest -vvv --junitxml=report.xml

      - name: Run mypy static type checker
        run: mypy --strict --junit-xml type_check_report.xml  .

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: |
            "report.xml"
            "type_check_report.xml"
        if: always()
